name: Develop Branch CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  check_branch_name:
    runs-on: self-hosted

    steps:
    - name: Check if PR is from a feature or release branch
      if: github.event.pull_request.base.ref == 'develop'
      run: |
        PR_BRANCH=${{ github.event.pull_request.head.ref }}
        if [[ $PR_BRANCH != feature/* && $PR_BRANCH != release/* && $PR_BRANCH != dependabot/* ]]; then
          echo "Error: Only branches starting with 'feature/' or 'release/' can be merged into 'develop'."
          exit 1
        fi

  build:
    needs: check_branch_name
    runs-on: self-hosted

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up secrets
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_FILE }}" | base64 --decode > ./test.json
        working-directory: ./cert
          
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GH_PACKAGES_TOKEN}}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ../cert/test.json
          PROJECT_ID: test-cmile-project